server:
  port: 24051
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    # PostgreSQL 연결 설정
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://postgres_new:5432/indigodb?charSet=EUC_KR  # DB명 확인 필요
    url: jdbc:postgresql://localhost:5432/indigodb?charSet=EUC_KR  # DB명 확인 필요
    username: interface_manager
    password: meta1234 # 실제 비밀번호로 수정
  jpa:
    # 데이터베이스 방언 설정 (PostgreSQL용)
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # 테이블 자동 생성 설정 (개발 환경: update / 운영 환경: none)
      ddl-auto: update
    show-sql: true        # 콘솔에 실행 SQL 출력
    properties:
      hibernate:
        format_sql: true  // SQL을 보기 좋게 포맷팅
        highlight_sql: true
        # 스키마에 CHAR(1) 등이 있으므로 정확한 매핑을 위해 사용
        jdbc:
          lob:
            non_contextual_creation: true
  # JSON 직렬화 설정 (CamelCase 유지)
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    serialization:
      fail-on-empty-beans: false
  activemq:
    broker-url: failover:(tcp://localhost:28001?wireFormat.maxInactivityDuration=0&wireFormat.cacheEnabled=false)

jms:
  receiver:
    destination: IF.AD2IMC.Q
  sender:
    destination: IF.IMC2AD.Q

# 로깅 설정 (쿼리 파라미터 값 확인용)
logging:
  file:
      name: /tmp/interface-manager.log  # 또는 톰캣 설치 경로 내 절대 경로
  level:
    root: INFO
    com.imc.interfacemanager: DEBUG
 #   org.hibernate.SQL: DEBUG
 #   org.hibernate.type.descriptor.sql.BasicBinder: TRACE # 쿼리에 바인딩되는 값('Y', 'N' 등) 출력